# Generated by Django 3.0.3 on 2022-12-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='market_id',
            field=models.IntegerField(),
        ),
    ]
