# Generated by Django 3.0.3 on 2022-11-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(max_length=50)),
                ('i', models.CharField(max_length=50)),
                ('o', models.CharField(max_length=50)),
                ('age', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('pswrd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clients_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_info', models.TextField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Clients')),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zp', models.IntegerField()),
                ('pswrd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Top_managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zp', models.IntegerField()),
                ('pswrd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reps_prods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Products')),
                ('rep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Reps')),
            ],
        ),
        migrations.AddField(
            model_name='reps',
            name='top_manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Top_managers'),
        ),
        migrations.CreateModel(
            name='Orders_prods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Clients_orders')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Markets_prods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Markets')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Products')),
            ],
        ),
        migrations.AddField(
            model_name='markets',
            name='id_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Reps'),
        ),
        migrations.AddField(
            model_name='markets',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Managers'),
        ),
        migrations.CreateModel(
            name='Clients_prods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.IntegerField()),
                ('count', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Clients')),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Markets')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.Products')),
            ],
        ),
    ]
